spring.application.name=crud-tallergo

spring.datasource.url=${DB_URL:jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:tallergo}}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.mariadb.jdbc.Driver}

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.messages.encoding=UTF-8
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG

spring.datasource.hikari.maximum-pool-size=10

app.upload-root=${APP_UPLOAD_PATH:uploads}
spring.web.resources.static-locations=classpath:/static/,file:${app.upload-root}/

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:fake-id}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:fake-secret}
spring.security.oauth2.client.registration.github.scope=read:user
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login

spring.mail.from=${SPRING_MAIL_FROM:noreply@example.com}
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:user}
spring.mail.password=${SPRING_MAIL_PASSWORD:pass}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.public-base-url=http://localhost:8080
app.password-reset.path=/auth/reset-password